export const TOP_PANEL_BRANDS = [
  'Jinko Solar',
  'LONGi Solar',
  'Trina Solar',
  'Canadian Solar',
  'JA Solar',
  'Qcells (Hanwha)',
  'First Solar',
  'Maxeon / SunPower',
  'REC Group',
  'Meyer Burger',
  'Astronergy',
  'Risen Energy',
  'Suntech',
  'Other / Generic',
];

export const TOP_INVERTER_BRANDS = [
  'Enphase Energy',
  'SolarEdge',
  'Fronius',
  'Growatt',
  'Huawei FusionSolar',
  'Sungrow',
  'Tesla Solar',
  'SMA Solar Technology',
  'Victron Energy',
  'GoodWe',
  'Deye',
  'Solis (Ginlong)',
  'Hoymiles',
  'APsystems',
  'Delta Electronics',
  'Other / Generic',
];

export const GLOBAL_COUNTRIES = [
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
];
