import { CheckIn } from '../types/checkin';

export const FALLBACK_MOCK_CHECKINS: CheckIn[] = [
  {
    id: 'mock-1',
    user_id: 'user-1',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 48.45,
    system_kwp: 8.50,
    efficiency_kwh_per_kwp: 5.70,
    notes: 'Peak production in Southern California today! Microinverters performing great.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-1',
      username: 'socal_sam',
      display_name: 'Sam Miller',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      country_code: 'US',
      city_region: 'Los Angeles',
      system_kwp: 8.50,
      panel_brand: 'Qcells (Hanwha)',
      inverter_brand: 'Enphase Energy',
      role: 'consumer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'mock-2',
    user_id: 'user-2',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 54.00,
    system_kwp: 10.00,
    efficiency_kwh_per_kwp: 5.40,
    notes: 'Commercial rooftop system in Sydney. Clean solar power.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-2',
      username: 'sydney_pv_pro',
      display_name: 'Shane (Sydney PV)',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      country_code: 'AU',
      city_region: 'Sydney',
      system_kwp: 10.00,
      panel_brand: 'Jinko Solar',
      inverter_brand: 'Fronius',
      role: 'installer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'mock-3',
    user_id: 'user-3',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 46.00,
    system_kwp: 9.20,
    efficiency_kwh_per_kwp: 5.00,
    notes: 'Strong solar irradiance in São Paulo today.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-3',
      username: 'sao_paulo_green',
      display_name: 'Lucas Silva',
      avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
      country_code: 'BR',
      city_region: 'São Paulo',
      system_kwp: 9.20,
      panel_brand: 'JA Solar',
      inverter_brand: 'Growatt',
      role: 'consumer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'mock-4',
    user_id: 'user-4',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 25.85,
    system_kwp: 5.50,
    efficiency_kwh_per_kwp: 4.70,
    notes: 'Clouds in KL afternoon, solid yield overall.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-4',
      username: 'kl_rooftop',
      display_name: 'Ken Tan',
      avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      country_code: 'MY',
      city_region: 'Kuala Lumpur',
      system_kwp: 5.50,
      panel_brand: 'LONGi Solar',
      inverter_brand: 'Sungrow',
      role: 'consumer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'mock-5',
    user_id: 'user-5',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 18.06,
    system_kwp: 4.20,
    efficiency_kwh_per_kwp: 4.30,
    notes: 'Surprisingly clear sky over London today.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-5',
      username: 'london_solar',
      display_name: 'Oliver Smith',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      country_code: 'GB',
      city_region: 'London',
      system_kwp: 4.20,
      panel_brand: 'REC Group',
      inverter_brand: 'SolarEdge',
      role: 'consumer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'mock-6',
    user_id: 'user-6',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 30.24,
    system_kwp: 7.20,
    efficiency_kwh_per_kwp: 4.20,
    notes: 'String inverters running smoothly.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-6',
      username: 'sg_cleantech',
      display_name: 'David Chen',
      avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      country_code: 'SG',
      city_region: 'Singapore',
      system_kwp: 7.20,
      panel_brand: 'Trina Solar',
      inverter_brand: 'Huawei FusionSolar',
      role: 'installer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'mock-7',
    user_id: 'user-7',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 24.60,
    system_kwp: 6.00,
    efficiency_kwh_per_kwp: 4.10,
    notes: 'Munich grid connection stable.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-7',
      username: 'munich_hans',
      display_name: 'Hans Weber',
      avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      country_code: 'DE',
      city_region: 'Munich',
      system_kwp: 6.00,
      panel_brand: 'Meyer Burger',
      inverter_brand: 'SMA Solar Technology',
      role: 'consumer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  },
  {
    id: 'mock-8',
    user_id: 'user-8',
    check_in_date: new Date().toISOString().slice(0, 10),
    kwh_generated: 20.00,
    system_kwp: 5.00,
    efficiency_kwh_per_kwp: 4.00,
    notes: 'Tokyo roof producing steadily.',
    is_dummy: true,
    created_at: new Date().toISOString(),
    profiles: {
      id: 'user-8',
      username: 'tokyo_sun',
      display_name: 'Kenji Sato',
      avatar_url: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150',
      country_code: 'JP',
      city_region: 'Tokyo',
      system_kwp: 5.00,
      panel_brand: 'Canadian Solar',
      inverter_brand: 'Deye',
      role: 'consumer',
      is_dummy: true,
      created_at: new Date().toISOString()
    }
  }
];
